apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hola-front
  template:
    metadata:
      labels:
        app: hola-front
    spec:
      containers:
      - name: frontend
        image: ghcr.io/raullopezepam/hola-front:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: SALUDO_USER
          value: "Hola"
