apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: hola-front # <--- ¡IMPORTANTE! Debe coincidir con el label del Deployment
  ports:
    - protocol: TCP
      port: 80         # Puerto por el que escucha el servicio
      targetPort: 3000 # Puerto donde corre la App de Node
      nodePort: 30080  # Puerto fijo para acceder desde fuera (esto es opcional)
